spring:
  datasource:
    url: jdbc:mysql://localhost:3306/programmersblog?serverTimezone=UTC
    username: root
    password: 1234567
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

delete:
   expiredCaptcha: 60