spring:
  datasource:
    url: jdbc:mysql://localhost:3306/programmersblog?serverTimezone=UTC
    username: root
    password: 1234567
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect